### ISSUE TITLE
Uninstall modules

### ISSUE THREAD

**Issue by Genaker** [yireo/magento2-replace-content-staging#2]
Does this module uninstall modules or works only with fresh installation? I have problem uninstall  staging.

**Comment by jissereitsma** [comment]
As you probably know, the official Magento procedure of uninstalling modules requires manual modifications of the `composer.json` and `composer.lock` files of your project in production. In short, it lacks. Needless to say, any other composer approach also lacks. Most agencies therefore simply deploy a new `composer.json` and `composer.lock` file to production and run things from there. In that, the `composer.json` trick in this repository simply extends from that.

Please note that this is NOT a module. It is a composer meta-package that simply ships with a `replace` trick. Do make sure to understand this `replace` trick inside out, by reading the relevant blogs on it. If you don't understand what it is, it is probably best to wait for an official Magento solution instead.

**Comment by Genaker** [comment]
Yes I understand that. I basically tried uninstall staging module before
and magento after doesn’t work. Some database error. Uninstall script
issues. Maybe if it is fresh installation it works, if it is project with
staging history it is impossible remove this modules.

**Comment by jissereitsma** [comment]
It would be useful if you could report the database error. If the error is indicating that the setup of a module A is called, while that module A is listed as enabled in `app/etc/config.php` while no longer available in `vendor`, then this is not related to this repository but simpy a Magento procedure of modifying the relevant `app/etc/config.php` entries. As of yet, I'm inclined to close this issue, unless you have something specific to report on the `replace` trick. Please note that this repository only (!) applies the `replace` trick, nothing more nothing less. So comments on setup procedures are outside of the scope of this project - they are things all Magento developers bump into sooner or later.

**Comment by Genaker** [comment]
For sure, feel free to close this issue! Thank you for your help!
